//Test the sending of a message using different technologies. For this version
//teh login requiremnents for the user are not enforced
//Allows access to basic utilities, eg., special error handler
import * as schema from "./../../schema.js";
//
//Resolve the reference to the mutall user's database class that is 
//automatically generated. 
import * as mutall_user from "./../../mutall_user.js";
//
//Resolve reference to the messenger which extends the autogenerated version
//with the send() method
import * as messenger from "./../messenger.js";
//Test the send method(
export function send() {
    //
    //Get the span element where to post the report
    const report = document.getElementById('result');
    //
    //You may have failed to define it in your form
    if (report === null)
        throw new schema.mutall_error('Result tag not found');
    //
    //Clear the output result, ready for output from this test
    report.innerHTML = "";
    //
    //Define the sender: S/he is a individual that is assumed to be
    //already registered. You get an exception if not registered.
    const sender = new mutall_user.user('pmuraya');
    //
    //Create an instance of the messenger class (whish is an extension of tj+the
    //mutall_user version) to send a 'Hello word' message under the 'Testing' 
    //subject. 
    const msg = new messenger.msg('Testng', 'Hello Word', sender);
    //
    //The recipient is a business in which the user is registered. You get an
    //exception if this is not the case
    const recipient = new mutall_user.business('mutall_data');
    //
    //Use the extended library to create an emailer. NB. This is not an auto-
    //generated class
    const emailer = new messenger.mailer(recipient);
    //
    //Send the hello message to the recipient group group using email
    const result = msg.send([emailer]);
    //
    //Compile the resulting response
    const response = result === 'ok' ? 'ok' : result.message;
    //
    //Show the response
    report.innerHTML = response;
    //
    //Test the send method using the twilio and mobitech sms technologies
    //Test the send method susing websocket technology
}
